name: Release docs bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '!docs/index.md'
      - '!docs/.vitepress/**'

permissions:
  contents: write

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build tarball (exclude index.md, .vitepress, public) without leading "."
        run: |
          set -euo pipefail
          VERSION="$(date -u +'%Y%m%d-%H%M')-${GITHUB_SHA::7}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

          # Create archive from docs/, exclude unwanted paths, and strip the "./" prefix in entries
          tar -C docs \
            --exclude='index.md' \
            --exclude='.vitepress' \
            --exclude='.vitepress/*' \
            --exclude='public' \
            --exclude='public/*' \
            --transform='s,^\./,,' \
            -czf "docs-${VERSION}.tar.gz" \
            .

          # helper files
          sha256sum "docs-${VERSION}.tar.gz" > "docs-${VERSION}.sha256"
          tar -tzf "docs-${VERSION}.tar.gz" | sort > "docs-${VERSION}-manifest.txt"

      - name: Create GitHub Release with archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "docs-${VERSION}" \
            --title "Docs ${VERSION}" \
            --notes "Auto-generated from $GITHUB_SHA" \
            "docs-${VERSION}.tar.gz" \
            "docs-${VERSION}.sha256" \
            "docs-${VERSION}-manifest.txt"
