name: Release docs bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '!docs/index.md'
      - '!docs/.vitepress/**'

permissions:
  contents: write

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build tarball (exclude index.md and .vitepress)
        run: |
          set -euo pipefail
          VERSION="$(date -u +'%Y%m%d-%H%M')-${GITHUB_SHA::7}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

          # собираем архив из *содержимого* каталога docs/ (без верхнего "."),
          # исключая index.md и .vitepress/**
          cd docs
          find . -mindepth 1 -maxdepth 1 \
            ! -name 'index.md' \
            ! -path './.vitepress' \
            ! -path './.vitepress/*' -print0 \
          | tar -czf "../docs-${VERSION}.tar.gz" --null -T -
          cd - >/dev/null

          # удобные вспомогательные файлы
          sha256sum "docs-${VERSION}.tar.gz" > "docs-${VERSION}.sha256"
          tar -tzf "docs-${VERSION}.tar.gz" | sort > "docs-${VERSION}-manifest.txt"

      - name: Create GitHub Release with archive
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "docs-${VERSION}" \
            --title "Docs ${VERSION}" \
            --notes "Auto-generated from $GITHUB_SHA" \
            "docs-${VERSION}.tar.gz" \
            "docs-${VERSION}.sha256" \
            "docs-${VERSION}-manifest.txt"
